name: Build

on:
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: docker.io/ciliconherve/synapse

jobs:
  check-sampleconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -e .
      - run: scripts-dev/generate_sample_config.sh --check

  lint:
    uses: "matrix-org/backend-meta/.github/workflows/python-poetry-ci.yml@v1"
    with:
      typechecking-extras: "all"

  lint-crlf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check line endings
        run: scripts-dev/check_line_terminators.sh

  # Dummy step to gate other tests on without repeating the whole list

  # Dummy step to gate other tests on without repeating the whole list
  linting-done:
    if: ${{ !cancelled() }} # Run this even if prior jobs were skipped
    needs:
    # Note(joseb): we ignore several upstream lint jobs such as pydantic, clippy, rustfmt, etc.
    # because our forked version doesn't include changes on rust or configuration data.
      - lint
      - lint-crlf
    runs-on: ubuntu-latest
    steps:
      - run: "true"

  containerize:
    if: ${{ !failure() }} # Allow previous steps to be skipped, but not fail
    needs: linting-done
    name: Build image
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - uses: actions/checkout@v2

    - name: Build image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        tags: |
          ${{ env.DOCKER_IMAGE_NAME }}:latest
